<?php $validate_age = 1; $minimum_age = $this->getMinimumAge(); ?> <script type="text/x-magento-init">
    {
       "*": {
           "ageValidation" : { "param" : "<?=$minimum_age?>"}
       }
    }</script><?php if ($validate_age == 1) : ?> <script>
    require([
        'jquery'
    ], function($) {
       
            
            $(".customer-dob input").addClass('validate-dob');
            
       
    });</script><?php endif; ?>