version: '3'
services:
   app:
       image: webdevops/php-apache-dev:8.1-alpine
       container_name: app
       restart: always
       user: application
       environment:
         - WEB_DOCUMENT_ROOT=/app/pub
         - PHP_DATE_TIMEZONE=EST
         - PHP_DISPLAY_ERRORS=1
         - PHP_MEMORY_LIMIT=4096M
         - PHP_MAX_EXECUTION_TIME=18000
         - PHP_POST_MAX_SIZE=500M
         - PHP_UPLOAD_MAX_FILESIZE=1024M
       volumes:
         - /c/xampps/htdocs/magento245:/app:cached
       ports:
         - "80:80"
         - "443:443"
         - "32823:22"
       links:
         - mysql
       networks:
          - app-network
   mysql:
       image: mariadb:10.4
       container_name: mysql
       restart: always
       ports:
         - "3307:3306"
       environment:
         - MYSQL_ROOT_PASSWORD=root
         - MYSQL_DATABASE=m245_db
       volumes:
         - db-data:/var/lib/mysql
       networks:
          - app-network
   phpmyadmin:
       container_name: phpmyadmin
       restart: always
       image: phpmyadmin/phpmyadmin:latest
       environment:
         - MYSQL_ROOT_PASSWORD=root
         - PMA_USER=root
         - PMA_PASSWORD=root
       ports:
         - "8080:80"
       links:
         - mysql:db
       depends_on:
         - mysql
       networks:
          - app-network
   elasticsearch:
     image: elasticsearch:7.17.5
     container_name: elasticsearch7
     ports:
       - "9200:9200"
       - "9300:9300"
     environment:
       "discovery.type": "single-node"
     networks:
       - app-network
     ports:
       - "9200:9200"
       - "9600:9600"
     networks:
       - app-network
volumes:
   db-data:
       external: false
networks:
  app-network:
    driver: bridge
