<?php
namespace WePay\Registrationcode\Model;

use Magento\Framework\Model\AbstractModel;

class Attribute extends AbstractModel
{
    protected function _construct()
    {
        $this->_init(\WePay\Registrationcode\Model\ResourceModel\Attribute::class);
//        parent::_construct(); // TODO: Change the autogenerated stub
    }

}
