<?php /** * * @category : WePay * @Package : WePay_AdditionalCustomerAttributes * @Author : WePay Extensions <support@wepayextensions.com> * @copyright Copyright 2018 © wepayextensions.com All right reserved * @license https://wepayextensions.com/LICENSE.txt */ ?> <script type="text/x-magento-init">
    {
        "*": {
            "additionalCustomerAttributes": {
                "hiddenFields": <?php /* @escapeNotVerified */ echo json_encode($this->helper('Magento\Catalog\Helper\Data')->getAttributeHiddenFields()); ?> }
        }
    }</script>