<?php

namespace Prasanna\Invitecode\Model;

use Magento\Framework\Model\AbstractModel;

class Invitecode extends AbstractModel
{
    protected function _construct()
    {
        $this->_init(\Prasanna\Invitecode\Model\ResourceModel\Invitecode::class);
        //parent::_construct(); // TODO: Change the autogenerated stub
    }
}
