<?php
/**
 *
 * @category : FME
 * @Package  : FME_AdditionalCustomerAttributes
 * @Author   : FME Extensions <support@fmeextensions.com>
 * @copyright Copyright 2018 © fmeextensions.com All right reserved
 * @license https://fmeextensions.com/LICENSE.txt
 */
/* @var $block \FME\AdditionalCustomerAttributes\Block\Element\Multiselect */
?>
<?php
$ElementClass = 'field field-' . $block->getAttributeId();
$ElementClass .= $block->isRequired() ? ' required' : '';

$attributeId = $block->getCurrentAttribute()->getAttributeId();
$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$storeId = $storeManager->getStore()->getId();
$optionCollectionFactory = $objectManager->create('\Magento\Eav\Model\ResourceModel\Entity\Attribute\Option\CollectionFactory');
$optionCollection = $optionCollectionFactory->create()
    ->setPositionOrder('asc')
    ->setAttributeFilter($attributeId)
    ->setStoreFilter($storeId)
    ->load();
?>
<div class="<?php /* @escapeNotVerified */ echo $ElementClass; ?>">
    <label class="label" for="<?php echo $block->getAttributeId()?>"><span><?php /* @escapeNotVerified */ echo $block->getLabel() ?></span></label>
    <div class="control">
        <?php
            if ($block->getIsEditable()) :
        ?>
        <input type="checkbox" name="<?php echo $block->getAttributeName('');?>" value="0"
            id="<?php echo $block->getAttributeId()."-0";?>"
            acode =  "<?php echo $block->getCurrentAttribute()->getAttributeCode(); ?>"
            dependable = "<?php echo $block->getCurrentAttribute()->getFmeDependable(); ?>"
            dcode = "<?php echo $block->getCurrentAttribute()->getFmeDcode(); ?>"
            did = "<?php echo $block->getCurrentAttribute()->getFmeDid(); ?>"
            dvalue = "<?php echo $block->getCurrentAttribute()->getFmeDvalue(); ?>"
            style  = "display: none;"
            checked="checked"
         />
        <?php endif;?>
        <?php //foreach ($block->getOptions() as $option):?>
        <?php foreach ($optionCollection as $option):?>
        <input <?php if (!$block->getIsEditable()) :?>disabled="disabled"<?php endif; ?> id="<?php echo $block->getAttributeId()."-".$option['option_id'];?>"
            type="checkbox" name="<?php echo $block->getAttributeName('');?>"
            acode =  "<?php echo $block->getCurrentAttribute()->getAttributeCode(); ?>"
            dependable = "<?php echo $block->getCurrentAttribute()->getFmeDependable(); ?>"
            dcode = "<?php echo $block->getCurrentAttribute()->getFmeDcode(); ?>"
            did = "<?php echo $block->getCurrentAttribute()->getFmeDid(); ?>"
            dvalue = "<?php echo $block->getCurrentAttribute()->getFmeDvalue(); ?>"
            value="<?php /* @escapeNotVerified */ echo $option['option_id']?>" <?php if ($block->isSelected($option['option_id'])):?> checked="checked"<?php endif;?>
            class="checkbox <?php if ($block->getValidateClasses()) : echo $block->getValidateClasses(); endif;?>"
             /><label for="<?php echo $block->getAttributeId()."-".$option['option_id'];?>"><?php echo $block->escapeHtml($option['value'])?></label><br />
        <?php endforeach;?>
        <?php if ($_tooltip = $block->getTooltip()) : ?>
        <div class="note"><?php /* @escapeNotVerified */ echo $_tooltip; ?></div>
        <?php endif; ?>
    </div>
</div>
