<?php
/**
 *
 * @category : FME
 * @Package  : FME_AdditionalCustomerAttributes
 * @Author   : FME Extensions <support@fmeextensions.com>
 * @copyright Copyright 2018 © fmeextensions.com All right reserved
 * @license https://fmeextensions.com/LICENSE.txt
 */
?>
<?php
$elementClass = 'field  field-' . $block->getAttributeId();
$elementClass .= $block->isRequired() ? ' required' : '';
?>
<div class="<?php /* @escapeNotVerified */ echo $elementClass; ?>">
    <label class="label" for="<?php echo $block->getAttributeId()?>"><span><?php /* @escapeNotVerified */ echo $block->getLabel() ?></span></label>
    <div class="control">
        <?php if ($block->getValue() != ""): ?>
            <a href="<?php /* @escapeNotVerified */ echo $block->getEscapedValue() ?>" target="_blank">
                <?php /* @escapeNotVerified */ echo $block->getLabel() ?>
            </a>
        <?php endif; ?>
        <br/>
        <?php if ($block->getIsEditable()) :?>
            <input type="file" size="<?php /* @escapeNotVerified */ echo trim($block->getMaxSize()); ?>"
                types="<?php /* @escapeNotVerified */ echo trim($block->getAllowedFileExtensions()); ?>"
                id="<?php echo $block->getAttributeId()?>"
                name="<?php /* @escapeNotVerified */ echo $block->getAttributeName()."_browsebutton"?>"
                value=""
                acode =  "<?php echo $block->getCurrentAttribute()->getAttributeCode(); ?>"
                dependable = "<?php echo $block->getCurrentAttribute()->getFmeDependable(); ?>"
                dcode = "<?php echo $block->getCurrentAttribute()->getFmeDcode(); ?>"
                did = "<?php echo $block->getCurrentAttribute()->getFmeDid(); ?>"
                dvalue = "<?php echo $block->getCurrentAttribute()->getFmeDvalue(); ?>"
                class="input-file <?php if ($block->getValue() == "" ) : echo $block->getValidateClasses(); endif; ?> <?php if ($block->getAllowedFileExtensions() != "" ) : echo "validate-fileextensions"; endif; ?>  <?php if ($block->getMaxSize() > 0 ) { echo "validate-filesize"; } ?>">
            <?php if ($block->getAllowedFileExtensions() != "") : ?>
                <br/>
                <div class="note extensions">
                    <?php /* @escapeNotVerified */ echo __("Allowed File Types: %1",trim($block->getAllowedFileExtensions())); ?>
                </div>
            <?php endif; ?>
            <?php if ($block->getMaxSize() > 0) : ?>
                <br/>
                <div class="note max_size">
                    <?php /* @escapeNotVerified */ echo __("Maximum File Size Allowed: %1MB",$block->getMaxSize()); ?>
                </div>
            <?php endif; ?>
            <input type="hidden" id="<?php echo $block->getAttributeId()?>_value" 
                name="<?php /* @escapeNotVerified */ echo $block->getAttributeName()?>_org_value"
                value="<?php /* @escapeNotVerified */ echo $block->getValue()?>" />
        <?php endif; ?>
        <?php if ($_tooltip = $block->getTooltip()) : ?>
            <br/>
            <div class="note"><?php /* @escapeNotVerified */ echo $_tooltip; ?></div>
        <?php endif; ?>
    </div>
</div>
