<?php
/**
 *
 * @category : FME
 * @Package  : FME_AdditionalCustomerAttributes
 * @Author   : FME Extensions <support@fmeextensions.com>
 * @copyright Copyright 2018 © fmeextensions.com All right reserved
 * @license https://fmeextensions.com/LICENSE.txt
 */
/* @var $block \FME\AdditionalCustomerAttributes\Block\Element\Select */
?>
<?php
$elementClass = 'field field-' . $block->getAttributeId();
$elementClass .= $block->isRequired() ? ' required' : '';
$attributeCode = $block->getCurrentAttribute()->getAttributeCode();

$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
//$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
$attributeRepository = $objectManager->create('\Magento\Eav\Model\Config');
$attribute = $attributeRepository->getAttribute('additionalcustomerattributes', $attributeCode);
$options = $attribute->getSource()->getAllOptions();
?>
<div class="<?php /* @escapeNotVerified */ echo $elementClass; ?>">
    <label class="label" for="<?php echo $block->getAttributeId()?>"><span><?php /* @escapeNotVerified */ echo $block->getLabel() ?></span></label>
    <div class="control">
        <select <?php if (!$block->getIsEditable()) :?>disabled="disabled"<?php endif; ?>  id="<?php echo $block->getAttributeId()?>"
            name="<?php /* @escapeNotVerified */ echo $block->getAttributeName()?>"
            acode =  "<?php echo $block->getCurrentAttribute()->getAttributeCode(); ?>"
            dependable = "<?php echo $block->getCurrentAttribute()->getFmeDependable(); ?>"
            dcode = "<?php echo $block->getCurrentAttribute()->getFmeDcode(); ?>"
            did = "<?php echo $block->getCurrentAttribute()->getFmeDid(); ?>"
            dvalue = "<?php echo $block->getCurrentAttribute()->getFmeDvalue(); ?>"
            class="multiselect <?php if ($block->getValidateClasses()) : echo $block->getValidateClasses(); endif;?>"
        >
        <?php //foreach ($block->getOptions() as $option):?>
        <?php foreach ($options as $option):?>
            <option value="<?php /* @escapeNotVerified */ echo $option['value']?>"
                <?php if ($option['value'] == $block->getValue()):?> selected="selected"<?php endif;?>>
                <?php echo $block->escapeHtml($option['label'])?>
            </option>
        <?php endforeach;?>
        </select>
        <?php if ($_tooltip = $block->getTooltip()) : ?>
        <div class="note"><?php /* @escapeNotVerified */ echo $_tooltip; ?></div>
        <?php endif; ?>
    </div>
</div>
