<?php
/**
 *
 * @category : FME
 * @Package  : FME_AdditionalCustomerAttributes
 * @Author   : FME Extensions <support@fmeextensions.com>
 * @copyright Copyright 2018 © fmeextensions.com All right reserved
 * @license https://fmeextensions.com/LICENSE.txt
 */
/* @var $block \FME\AdditionalCustomerAttributes\Block\Element\Boolean */
?>
<?php
$ElementClass = 'field field-' . $block->getAttributeId();
$ElementClass .= $block->isRequired() && !$block->getIsEditable()? ' required' : '';
?>
<div class="<?php /* @escapeNotVerified */ echo $ElementClass; ?>">
    <label class="label" for="<?php echo $block->getAttributeId()?>"><span><?php /* @escapeNotVerified */ echo $block->getLabel() ?></span></label>
    <div class="control">
        <select 
          id="<?php echo $block->getAttributeId()?>"
          name="<?php /* @escapeNotVerified */ echo $block->getAttributeName()?>"
          acode =  "<?php echo $block->getCurrentAttribute()->getAttributeCode(); ?>"
          dependable = "<?php echo $block->getCurrentAttribute()->getFmeDependable(); ?>"
          dcode = "<?php echo $block->getCurrentAttribute()->getFmeDcode(); ?>"
          did = "<?php echo $block->getCurrentAttribute()->getFmeDid(); ?>"
          dvalue = "<?php echo $block->getCurrentAttribute()->getFmeDvalue(); ?>"
          class="select <?php if ($block->getValidateClasses()) : echo $block->getValidateClasses(); endif;?>"
          data-form-part="customer_form">
        <?php foreach ($block->getOptions() as $option):?>
        <option value="<?php /* @escapeNotVerified */ echo $option['value']?>"<?php if ($option['value'] == $block->getValue()):?> selected="selected"<?php endif;?>><?php echo $block->escapeHtml($option['label'])?></option>
        <?php endforeach;?>
        </select>
        <?php if ($_tooltip = $block->getTooltip()) : ?>
        <div class="note"><?php /* @escapeNotVerified */ echo $_tooltip; ?></div>
        <?php endif; ?>
    </div>
</div>
