<?php
/**
 *
 * @category : FME
 * @Package  : FME_AdditionalCustomerAttributes
 * @Author   : FME Extensions <support@fmeextensions.com>
 * @copyright Copyright 2018 © fmeextensions.com All right reserved
 * @license https://fmeextensions.com/LICENSE.txt
 */
/* @var $block \FME\AdditionalCustomerAttributes\Block\Element\Multiselect */
?>
<?php
$ElementClass = 'admin__field field field-' . $block->getAttributeId();
$ElementClass .= $block->isRequired() && !$block->getIsEditable()? ' required _required' : '';
?>
<div class="<?php /* @escapeNotVerified */ echo $ElementClass; ?>">
    <label class="label" for="<?php echo $block->getAttributeId()?>"><span><?php /* @escapeNotVerified */ echo $block->getLabel() ?></span></label>
    <div class="control">

        <?php foreach ($block->getOptions() as $option):  ?>
        <input id="<?php echo $block->getAttributeId()."-".$option['value'];?>"
            type="checkbox" 
            attribute_code="<?php echo $block->getAttributeName(); ?>"
            name="<?php echo $block->getAttributeName($option['value']);?>"
            acode =  "<?php echo $block->getCurrentAttribute()->getAttributeCode(); ?>"
            dependable = "<?php echo $block->getCurrentAttribute()->getFmeDependable(); ?>"
            dcode = "<?php echo $block->getCurrentAttribute()->getFmeDcode(); ?>"
            did = "<?php echo $block->getCurrentAttribute()->getFmeDid(); ?>"
            dvalue = "<?php echo $block->getCurrentAttribute()->getFmeDvalue(); ?>"
            value="<?php /* @escapeNotVerified */ echo $option['value']?>" <?php if ($block->isSelected($option['value'])):?> checked="checked"<?php endif;?>
            class="checkbox <?php if ($block->getValidateClasses()) : echo 'validate-one-required-by-name-checkbox'; endif;?>"
            data-form-part="customer_form"
            /><label for="<?php echo $block->getAttributeId()."-".$option['value'];?>"><?php echo $block->escapeHtml($option['label'])?></label><br />
        <?php endforeach;?>
        <?php if ($_tooltip = $block->getTooltip()) : ?>
        <div class="note"><?php /* @escapeNotVerified */ echo $_tooltip; ?></div>
        <?php endif; ?>
    </div>
</div>
