<?php
namespace Prasanna\Invitecode\Model\ResourceModel\Invitecode;

use Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection;
use Prasanna\Invitecode\Model\Invitecode as Model;
use Prasanna\Invitecode\Model\ResourceModel\Invitecode as ResourceModel;

class Collection extends AbstractCollection
{
    protected $_idFieldName = 'entity_id';

    protected function _construct()
    {
        $this->_init(Model::class, ResourceModel::class);
        //parent::_construct(); // TODO: Change the autogenerated stub
    }
}
